// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlankLines: typeof import('./src/components/blog/BlankLines.vue')['default']
    BlogInfo: typeof import('./src/components/global/BlogInfo.vue')['default']
    Counter: typeof import('./src/components/global/Counter.vue')['default']
    Footer: typeof import('./src/components/global/Footer.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timer: typeof import('./src/components/blog/Timer.vue')['default']
  }
}
